# Base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy the application code into the container
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt

# Set the entry point for the container
ENTRYPOINT [ "python", "app.py" ]